CREATE TABLE IF NOT EXISTS works (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug TEXT NOT NULL UNIQUE,
    title TEXT NOT NULL,
    author TEXT,
    source_language TEXT NOT NULL,
    planned_target_languages TEXT,
    period TEXT,
    genre TEXT,
    priority TEXT NOT NULL DEFAULT 'medium',
    status TEXT NOT NULL DEFAULT 'candidate',
    source_provenance TEXT,
    translation_plan TEXT,
    license_status TEXT,
    notes TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS source_text_versions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    work_id BIGINT NOT NULL REFERENCES works(id) ON DELETE CASCADE,
    version_label TEXT NOT NULL,
    source_type TEXT,
    source_citation TEXT,
    source_url TEXT,
    text_hash TEXT,
    imported_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    notes TEXT,
    UNIQUE (work_id, version_label)
);

CREATE TABLE IF NOT EXISTS translations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    work_id BIGINT NOT NULL REFERENCES works(id) ON DELETE CASCADE,
    translator TEXT,
    translation_label TEXT NOT NULL,
    target_language TEXT NOT NULL DEFAULT 'English',
    publication_year INTEGER,
    publication_date TEXT,
    edition_citation TEXT,
    provenance TEXT,
    source_url TEXT,
    download_url TEXT,
    license_status TEXT,
    rights_statement TEXT,
    translation_source_type TEXT NOT NULL DEFAULT 'existing_human_translation',
    is_machine_generated BOOLEAN NOT NULL DEFAULT false,
    text_hash TEXT,
    imported_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    notes TEXT,
    UNIQUE (work_id, translation_label)
);

CREATE TABLE IF NOT EXISTS aligned_segments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    work_id BIGINT NOT NULL REFERENCES works(id) ON DELETE CASCADE,
    source_version_id BIGINT REFERENCES source_text_versions(id) ON DELETE SET NULL,
    translation_id BIGINT REFERENCES translations(id) ON DELETE SET NULL,
    segment_ref TEXT NOT NULL,
    segment_order INTEGER NOT NULL,
    alignment_level TEXT NOT NULL DEFAULT 'passage',
    alignment_status TEXT NOT NULL DEFAULT 'imported',
    source_text TEXT NOT NULL,
    target_text TEXT NOT NULL,
    source_token_count INTEGER NOT NULL,
    target_token_count INTEGER NOT NULL,
    source_char_count INTEGER NOT NULL,
    target_char_count INTEGER NOT NULL,
    source_syllable_count INTEGER,
    target_syllable_count INTEGER,
    metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
    text_hash TEXT,
    imported_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (work_id, translation_id, segment_ref, alignment_level)
);

CREATE INDEX IF NOT EXISTS aligned_segments_work_idx
    ON aligned_segments(work_id, segment_order);

CREATE INDEX IF NOT EXISTS aligned_segments_translation_idx
    ON aligned_segments(translation_id);

CREATE TABLE IF NOT EXISTS analysis_runs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    corpus_label TEXT NOT NULL,
    metric TEXT NOT NULL,
    baseline_model TEXT NOT NULL,
    feature_space TEXT NOT NULL,
    alignment_level TEXT,
    segment_count INTEGER NOT NULL,
    source_length_column TEXT NOT NULL,
    target_length_column TEXT NOT NULL,
    intercept DOUBLE PRECISION NOT NULL,
    slope DOUBLE PRECISION NOT NULL,
    r2 DOUBLE PRECISION NOT NULL,
    rmse DOUBLE PRECISION NOT NULL,
    residual_std DOUBLE PRECISION NOT NULL,
    source_feature_count INTEGER NOT NULL DEFAULT 0,
    target_feature_count INTEGER NOT NULL DEFAULT 0,
    source_predictor_r2 DOUBLE PRECISION,
    target_predictor_r2 DOUBLE PRECISION,
    parameters JSONB NOT NULL DEFAULT '{}'::jsonb,
    notes TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS segment_residuals (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    analysis_run_id BIGINT NOT NULL REFERENCES analysis_runs(id) ON DELETE CASCADE,
    aligned_segment_id BIGINT NOT NULL REFERENCES aligned_segments(id) ON DELETE CASCADE,
    source_length DOUBLE PRECISION NOT NULL,
    target_length DOUBLE PRECISION NOT NULL,
    expected_target_length DOUBLE PRECISION NOT NULL,
    residual DOUBLE PRECISION NOT NULL,
    standardized_residual DOUBLE PRECISION,
    UNIQUE (analysis_run_id, aligned_segment_id)
);

CREATE INDEX IF NOT EXISTS segment_residuals_run_residual_idx
    ON segment_residuals(analysis_run_id, residual);

CREATE TABLE IF NOT EXISTS residual_predictors (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    analysis_run_id BIGINT NOT NULL REFERENCES analysis_runs(id) ON DELETE CASCADE,
    side TEXT NOT NULL CHECK (side IN ('source', 'target')),
    feature TEXT NOT NULL,
    coefficient DOUBLE PRECISION NOT NULL,
    segment_count INTEGER NOT NULL,
    mean_residual_with_feature DOUBLE PRECISION,
    mean_residual_without_feature DOUBLE PRECISION,
    example_refs JSONB NOT NULL DEFAULT '[]'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (analysis_run_id, side, feature)
);

CREATE INDEX IF NOT EXISTS residual_predictors_run_side_coeff_idx
    ON residual_predictors(analysis_run_id, side, coefficient);

CREATE TABLE IF NOT EXISTS site_builds (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    analysis_run_id BIGINT REFERENCES analysis_runs(id) ON DELETE SET NULL,
    output_path TEXT,
    deployed_to TEXT,
    status TEXT NOT NULL DEFAULT 'generated',
    message TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE works
    ADD COLUMN IF NOT EXISTS planned_target_languages TEXT;

ALTER TABLE works
    ADD COLUMN IF NOT EXISTS translation_plan TEXT;

DROP VIEW IF EXISTS corpus_inventory;

CREATE VIEW corpus_inventory AS
SELECT
    w.slug,
    w.title,
    w.author,
    w.source_language,
    coalesce(
        nullif(string_agg(DISTINCT t.target_language, '; ' ORDER BY t.target_language), ''),
        w.planned_target_languages
    ) AS target_languages,
    w.genre,
    w.priority,
    w.status,
    count(s.id)::integer AS segment_count,
    coalesce(sum(s.source_token_count), 0)::integer AS source_tokens,
    coalesce(sum(s.target_token_count), 0)::integer AS target_tokens
FROM works w
LEFT JOIN aligned_segments s ON s.work_id = w.id
LEFT JOIN translations t ON t.id = s.translation_id
GROUP BY
    w.slug,
    w.title,
    w.author,
    w.source_language,
    w.planned_target_languages,
    w.genre,
    w.priority,
    w.status
ORDER BY
    CASE w.priority
        WHEN 'high' THEN 1
        WHEN 'medium' THEN 2
        ELSE 3
    END,
    w.source_language,
    w.title;
