#!/usr/bin/env python3
"""Run wordspend residual analysis from CSV or PostgreSQL."""

from __future__ import annotations

import argparse
from pathlib import Path

import pandas as pd

from wordspend.analysis import analyze_translation_spend, write_analysis_outputs
from wordspend.db import connect, fetch_segments, save_analysis_result


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--input", help="CSV with source_text and target_text columns.")
    parser.add_argument("--from-db", action="store_true", help="Read aligned segments from PostgreSQL.")
    parser.add_argument("--work", action="append", dest="works", help="Restrict to a work slug. Repeatable.")
    parser.add_argument("--limit", type=int, default=0)
    parser.add_argument("--metric", default="tokens", choices=["tokens", "characters", "syllables"])
    parser.add_argument("--baseline", default="log", choices=["log", "linear"])
    parser.add_argument("--min-df", type=int, default=2)
    parser.add_argument("--top-n", type=int, default=40)
    parser.add_argument("--max-features", type=int, default=2000)
    parser.add_argument("--corpus-label", default="all")
    parser.add_argument("--output-dir", default="build/analysis")
    parser.add_argument("--save-db", action="store_true")
    args = parser.parse_args()

    if args.from_db:
        with connect() as conn:
            frame = fetch_segments(conn, work_slugs=args.works, limit=args.limit if args.limit > 0 else None)
    elif args.input:
        frame = pd.read_csv(args.input)
        if args.limit and args.limit > 0:
            frame = frame.head(args.limit)
    else:
        raise SystemExit("Use --from-db or --input.")

    result = analyze_translation_spend(
        frame,
        metric=args.metric,
        baseline=args.baseline,
        min_df=args.min_df,
        top_n=args.top_n,
        max_features=args.max_features,
        corpus_label=args.corpus_label,
    )
    if not result["available"]:
        raise SystemExit(result["message"])

    output_dir = Path(args.output_dir)
    write_analysis_outputs(result, output_dir)
    print(f"Wrote analysis outputs to {output_dir}")
    print(result["metrics"])

    if args.save_db:
        with connect() as conn:
            run_id = save_analysis_result(conn, result, notes=f"Generated by scripts/run_analysis.py into {output_dir}")
        print(f"Saved analysis_run_id={run_id}")


if __name__ == "__main__":
    main()
